services:
  pizza_db:
    image: postgres:latest
    container_name: pizza_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - '../.env'
    networks:
      - pizza_window

networks:
      pizza_window:

volumes:
  pg_data: