services:
  postgres:
    image: postgres:latest
    container_name: pizza_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - '../.env'

volumes:
  pg_data: